### ISSUE TITLE
vs2017和2019preview都安装失败

### ISSUE THREAD

**Issue by maxwelltsai1536** [yuzd/AntDeployAgent#11]
vs2019preview ![image](https://user-images.githubusercontent.com/26304944/54652369-a0641c80-4af1-11e9-871c-05ad7956ed50.png)
vs2017 
![image](https://user-images.githubusercontent.com/26304944/54652508-0d77b200-4af2-11e9-9b0b-f0f42ce839db.png)

**Comment by yuzd** [comment]
暂不支持vs2019 preview 等2019出来在支持
vs2017安装失败 是偶发现象我目前也没有找到原因。请参考https://qiita.com/skytomo221/items/a52641eabf033fc27319
重启机器或者升级vs试试看，谢谢支持

**Comment by maxwelltsai1536** [comment]
升级vs解决
