### ISSUE TITLE
window server 2012  agent  安装失败 ：系统错误 1067  

### ISSUE THREAD

**Issue by yeibl** [yuzd/AntDeployAgent#12]
错误应用程序名称: AntDeployAgentWindowsService.exe，版本: 3.1.0.0，时间戳: 0x86a4e6a9
错误模块名称: KERNELBASE.dll，版本: 6.3.9600.19178，时间戳: 0x5bc10573
异常代码: 0xe0434352
错误偏移量: 0x00015ef8
错误进程 ID: 0x2834
错误应用程序启动时间: 0x01d4dec3f4660ee7
错误应用程序路径: D:\software\AntDeployAgent-master\AntDeployAgentWindowsService.exe
错误模块路径: C:\Windows\SYSTEM32\KERNELBASE.dll
报告 ID: 3221a755-4ab7-11e9-80d7-877b9d19ae53
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by yuzd** [comment]
请使用控制台方式运行，如果报错可以看到更详细的错误内容，如果出现错误内容麻烦在贴上来谢谢

**Comment by yeibl** [comment]
控制台程序是可以正常运行的，就是以windows 服务的时候会报这个错误

**Comment by yuzd** [comment]
@yeibl agent更新了 请用最新的试试看

**Comment by yeibl** [comment]
@yuzd 问题已解决，感谢！
