### ISSUE TITLE
不管是直接运行控制台，还是使用sc命令，都是这样报错，好奇怪

### ISSUE THREAD

**Issue by xuxuzhaozhao** [yuzd/AntDeployAgent#14]
![image](https://user-images.githubusercontent.com/21983146/54735086-e4811b00-4bde-11e9-8057-582e0231bc60.png)

**Comment by xuxuzhaozhao** [comment]
不知道这句sc命令是不是不对
```
sc create AntDeployTest binPath="C:\Users\Administrator\Desktop\AntDeployAgent-master\AntDeployAgentWindowsService.exe"
```

**Comment by yuzd** [comment]
检查服务器是否安装了netframework4.6 或以上

**Comment by rebelboy** [comment]
缺少DLL文件吧
System.IO.FileNotFoundException: 未能加载文件或程序集“AntDeployAgentWindows, Version=3.2.0.0, Culture=neutral,

**Comment by yuzd** [comment]
我的锅 刚提交漏掉了一个AntDeployAgentWindows.dll，重新下载下agent。。
