### ISSUE TITLE
服务启动成功又停止，事件管理器错误如下

### ISSUE THREAD

**Issue by lic0914** [yuzd/AntDeployAgent#15]
事件管理器ErrorInfo
无法启动服务。System.IO.FileNotFoundException:  未能加载文件或程序集“AntDeployAgentWindows, Version=3.2.0.0, Culture=neutral,  PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件。文件名:“AntDeployAgentWindows,  Version=3.2.0.0, Culture=neutral, PublicKeyToken=null” 在  AntDeployAgentWindowsService.AntDeployAgentWindowsService.OnStart(String[] args)  在 System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state) 警告:  程序集绑定日志记录被关闭。要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]  (DWORD)设置为 1。注意: 会有一些与程序集绑定失败日志记录关联的性能损失。要关闭此功能，请移除注册表值  [HKLM\Software\Microsoft\Fusion!EnableLog]。
-- | -- | -- | --

**Comment by yuzd** [comment]
我的锅 刚提交漏了一个dll。已补上

**Comment by lic0914** [comment]
少了个文件 没看到 现在 看到了

**Comment by lic0914** [comment]
我还说呢 这难道下载不完全么

**Comment by lic0914** [comment]
谢谢啦

**Comment by yuzd** [comment]
哈 谢谢支持
