### ISSUE TITLE
插件支持2013吗

### ISSUE THREAD

**Issue by BlueDemonChicken** [yuzd/AntDeployAgent#19]
我从https://marketplace.visualstudio.com/items?itemName=nainaigu.AntDeploy
下载的是2017的。
有支持2013的吗？
另外agent git一直下载失败。

**Comment by yuzd** [comment]
目前不支持vs2013哦 不过也是可以支持的 我得研究下
可以加qq群 qq群文件有 群号：488312978

**Comment by yuzd** [comment]
@BlueDemonChicken 你加下群 我给你个vs2013 试试看？

**Comment by yuzd** [comment]
@BlueDemonChicken  3.7版本已支持vs2013了 请更新到最新版试试
