### ISSUE TITLE
站点名称包含下划线

### ISSUE THREAD

**Issue by weskinglf** [yuzd/AntDeployAgent#20]
我的iis站点名称包含下划线，结果发布之后下划线都不见了

**Comment by yuzd** [comment]
我测试了下 iis上的站点名称如果你设置有下划线的话 发布后还是会有下划线的啊 如下图 
![image](https://user-images.githubusercontent.com/16083659/55400779-60854680-5581-11e9-9501-79e923f9fe98.png)

**Comment by weskinglf** [comment]
<img width="627" alt="WechatIMG126" src="https://user-images.githubusercontent.com/6645576/55405344-692f4a00-558c-11e9-8f3c-74009af987f1.png">
貌似是另外一个问题

**Comment by weskinglf** [comment]
<img width="355" alt="WechatIMG127" src="https://user-images.githubusercontent.com/6645576/55405487-c3300f80-558c-11e9-8821-74a4bd1ce746.png">
以上是iis的站点名称

**Comment by yuzd** [comment]
看样子是你agent不是已管理员方式启动的 加群反馈吧

**Comment by weskinglf** [comment]
好的。谢谢

**Comment by weskinglf** [comment]
你好，我试用管理员方式运行，可以正常发布，谢谢！
