### ISSUE TITLE
发布到IIS报错

### ISSUE THREAD

**Issue by squarezx** [yuzd/AntDeployAgent#21]
你好，今天发现升级到4.0版本后发布报错，之前都是正常的

![image](https://user-images.githubusercontent.com/6355288/56072575-43474800-5dcb-11e9-8dc7-b2202020a3a1.png)

**Comment by yuzd** [comment]
错误提示是需要升级agent。。。

**Comment by yuzd** [comment]
4.0版本涉及流程改变所以必须得升级一下agent
