### ISSUE TITLE
IIS部署：网站名称配置下拉优化

### ISSUE THREAD

**Issue by haojiefu007** [yuzd/AntDeployAgent#22]
![image](https://user-images.githubusercontent.com/25316390/56349602-72aaea00-61fb-11e9-9002-866c9770d25a.png)

IIS部署：有的时候一个项目可能有多个站点(dev,test,prod)，网站名称能否做成下拉列表？

**Comment by yuzd** [comment]
好的 后面计划考虑 网站名称随着环境走 可以加群提意见
