### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by SplendidDream** [yuzd/AntDeployAgent#26]
试用了以下，有很多便捷的地方，基础功能都已经满足。但有一些建议(针对 6.46版本)：
1。界面美化及布局调整，主要有以下几点：
a.窗体控件 风格 不统一。能否使用 wpf 开源 主题开发？
b.界面 布局是否可以调整？比如 进度展示 和 发布日志 能在一起显示。发布配置中的布局能否改善更加合理。
2. 性能问题。每次点击发布按钮后窗体都会假死，发布结束后立即恢复。这里的长时间逻辑能否改成异步或者在另外开一个进程处理呢？
3.能够加入发布密码策略？实际项目中正式环境不可能每个人都能发布。但是 目前只要安装插件的人都可以读取到发布配置进行发布操作。我看到服务器配置中有mac地址限制。是做这个用的么？
4.发布配置的排除规则 配置 目前好像不生效。排除的文件也被打包发布到服务器了。

**Comment by yuzd** [comment]
1. 界面美化 布局问题
=> 这个我目前没 有打算花费精力去搞界面(我对界面美化不擅长)，本身是开源项目我期待有人帮忙加入一起搞！
2. 性能问题
=> 你说的这个目前我没有遇到过呢。因为本身是放在另外一个线程处理的。AntDeploy发布界面是不会卡死的，遇到的话你能加群反馈下？
3. 发布密码策略？
=> 目前AntDeploy的配置文件比较重要，如果是用git团队合作 AntDeploy.json配置文件建议设置ignore不提交！mac地址是针对agent上限制逻辑，因为agent只有windows服务器才有效，所以mac地址校验是只针对windows服务器发布的
4. 发布的排除规则 
=> 采用的是相对地址 建议查看  https://github.com/yuzd/AntDeployAgent/issues/8 教程！
感谢建立， 请加群 一起探讨
