### ISSUE TITLE
出于安全考虑，token应该支持不存储在配置文件中，在发布时弹出对话框输入token

### ISSUE THREAD

**Issue by jrt324** [yuzd/AntDeployAgent#27]
出于安全考虑，token应该支持不存储在配置文件中，在发布时弹出对话框输入token
特别是基于vs发布的情况，配置文件直接写在项目中，开发组成员都能看见，不太安全

**Comment by yuzd** [comment]
针对安全考虑
建议AntDeploy.json的配置文件不要上传的git 或 svn。。设置下排除规则
或者设置下mac白名单功能(可以在agent的配置文件设置白名单mac)。
