### ISSUE TITLE
IIS站点名称WebSiteName不支持包含有空格的情况

### ISSUE THREAD

**Issue by jrt324** [yuzd/AntDeployAgent#28]
IIS站点名称WebSiteName不支持包含有空格的情况，发布失败
如果把站点名称中的空格去掉，就能发布成功

**Comment by yuzd** [comment]
嗯 。是不能包含空格的。你们有需要发布带有空格的？

**Comment by jrt324** [comment]
是的，原来站点创建的时候有空格的，比如  ”某某项目 - Api”   ”某某项目 - web”
不过总体影响不大，改一下站点名称就行了，只是之前浪费了很多时间一直发布不成功，最后才发现是空格引起的，如果能修复这个bug最好了，不能修复，最好是提醒一下用户

**Comment by yuzd** [comment]
哦 我后面修复下。。

**Comment by yuzd** [comment]
我看了下带空格是没问题的，可以发布成功。

![image](https://images4.c-ctrip.com/target/zb0915000000ypwe30D6E.png)
