### ISSUE TITLE
使用Docker Linux 如何指定细节

### ISSUE THREAD

**Issue by zenglei286** [yuzd/AntDeployAgent#29]
比如怎么指定发布到指定到服务器的目录 下，Docker实例的名字，怎么指定

**Comment by yuzd** [comment]
不支持指定服务器的目录 默认是发布到服务器的 antdeploy目录
不支持指定Docker实例的名字 默认是 项目 d_{项目名称}
因为考虑到发布界面配置的东西太多了，所以您想要实现的话 可以自己fork一份改下代码。
