### ISSUE TITLE
发布到docker 的 run 命令

### ISSUE THREAD

**Issue by Laimic** [yuzd/AntDeployAgent#31]
请问下 指定 Dockerfile 的 Expose 为 5000 的话
看到 run 命令就会是 5000:5000
有没有办法指定 run 命令是 8080:5000 ..

**Comment by yuzd** [comment]
有的，如果你的项目没有dockerfile的话，可以直接在发布窗口的端口填写的地方填写 8080:5000
如果有dockerfile的话 可以参考群文件里面有一个dockerfile模板里面有端口约定例子
