### ISSUE TITLE
Docker 打包上传镜像仓库，能登陆，上传失败。

### ISSUE THREAD

**Issue by guo-chsh** [yuzd/AntDeployAgent#33]
15:10:59|WARN|【Server】[upload image] - Login Succeeded  
15:10:59|ERROR|【Server】[upload image] - Fail  

阿里云，腾讯云都这样， 本地手动docker push是可以的。
哪有具体错误异常日志？

**Comment by guo-chsh** [comment]
另外是否能多支持点docker run 的参数？ --newtwork  -e 等等

**Comment by yuzd** [comment]
我发了一个更新
加了日志（辅助查看为什么upload image失败）
和支持 --network -e等其他参数

https://marketplace.visualstudio.com/items?itemName=nainaigu.AntDeployVsix

期待后续你的反馈

**Comment by guo-chsh** [comment]
Thanks,
看到异常日志了
docker run 的参数也可以用

两个建议
1.配置镜像上传--镜像地址 写下注释，因为镜像地址一般都是copy过来的（阿里，腾讯）点地址自动复制到粘贴板， 但实际上ccr.ccs.tencentyun.com 才是真正地址，我的异常由此而来。
2.dockerfile加些参数，例如：from 自己的基础镜像， 或是 增加RUN （用来执行apt-get ），这样会更灵活一点。

**Comment by yuzd** [comment]
@LlaneGuo 如果你的项目有Dockfile，会用你自定义的Dockfile，这个功能可以满足复杂的自定义需求

**Comment by guo-chsh** [comment]
@yuzd 不走我的Dockerfile，无论放主目录sln一起，还是放在项目csproj文件夹里都不行， 需要配置什么吗？

**Comment by yuzd** [comment]
是因为你没有设置拷贝吧？

**Comment by guo-chsh** [comment]
你说的对，确实没复制， 可以了
