### ISSUE TITLE
请问，能否设置成部署什么目录自动备份什么目录

### ISSUE THREAD

**Issue by yus1977** [yuzd/AntDeployAgent#34]
有时发布时，只发布一个目录，比如bin或views。能不能默认只备份发布的目录。
目前备份是所有目录 - 忽略目录

**Comment by yuzd** [comment]
你发布用的是选择指定目录发布吗？

**Comment by yus1977** [comment]
是的，指定目录发布时，服务器只备份发布的目录

**Comment by yuzd** [comment]
应该可以 我看看

**Comment by yus1977** [comment]
Thanks！

**Comment by yuzd** [comment]
你说的是备份的话 其实可以在agent的配置文件里面设置不备份的

**Comment by yus1977** [comment]
还是备份一下好，万一有问题还可以快速恢复

**Comment by yuzd** [comment]
我看了下，按照你说的会出现问题

比如 第一次你全量发布 有 a b c 三个文件
第二次你增量发布 只有b
第三次你全量发布 有b和c

然后你选择回滚到第二次，那么你想只备份b 没有c。那么就会导致实际上回滚的并不对！

如果你是增量发布的话 会把全部复制过来这样才能真正的无错误的快速回滚。
如果你觉得增量发布也要copy全部会导致占用太大磁盘，你可以设置忽略指定目录可以解决 。
