### ISSUE TITLE
Docker中的 Other没跟着Env改变而改变

### ISSUE THREAD

**Issue by dazhu6666** [yuzd/AntDeployAgent#35]
Docker中的 Other没跟着Env改变而改变   Volume会变

**Comment by dazhu6666** [comment]
另外，如果DeploySetting设置了ignoreRule之后，好像只对第一个服务器生效，
例如我增加了  /runtimes?.+
分别配置两个环境，然后第一个环境下 文件夹被排除没打包（正确）
第二个环境下，文件夹没被排除

**Comment by yuzd** [comment]
在设置tab里面可以把一个环境的ignoreRule复制到另外一个环境 你看下

**Comment by dazhu6666** [comment]
OK。。。。看到了，不过点下面的copy from other evn  如果是没填的情况下。会报错

**Comment by yuzd** [comment]
不填的话只不过不用而已不会报错呀

**Comment by yuzd** [comment]
我测试了 docker下的 other配置 是随着 环境名称走的呀
