### ISSUE TITLE
当目标服务器硬盘容量不足时，会没反应

### ISSUE THREAD

**Issue by dazhu6666** [yuzd/AntDeployAgent#36]
发布时如果目标服务器硬盘容量不足时，upload没反应，并未提醒，log也没反应显示

**Comment by yuzd** [comment]
应该是磁盘不够导致服务中断了吧 你配置了定时清理了么？agent的配置文件可以配置 最多保留多少个版本的记录 你看下配置文件 有注释说明的

**Comment by dazhu6666** [comment]
有时候是其它程序的日志或者各种原因导致硬盘容量不够，我意思程序发布的时候可以提示一下。。。如果能检测到的话

**Comment by yuzd** [comment]
我明白你的意思了。
因为已经不够用的话 服务就已经是中断的 我也没法提示。
所以得每次发布的时候去检测下剩余的。设定一个阈值 低于多少的话就提示出来 你觉得这样ok吗？

**Comment by dazhu6666** [comment]
也可以。。挺给力的
