### ISSUE TITLE
当命名需要添加sudo的时候，无法创建容器

### ISSUE THREAD

**Issue by dazhu6666** [yuzd/AntDeployAgent#37]

**Comment by yuzd** [comment]
非root账户吗

**Comment by dazhu6666** [comment]
是的。。能自动加上吗？

**Comment by yuzd** [comment]
那sudo 不用验证填密码吗

**Comment by yuzd** [comment]
是哪个命令 报出来权限不够

**Comment by dazhu6666** [comment]
14:49:31|ERROR|【Server】Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&nocache=1&rm=1&session=pv63ke2e9o2gboil0by35x598&shmsize=0&t=tyjxcubusinessmicroservice%3A20201119144929&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
  
14:49:31|ERROR|【Server】build image fail  



不用密码的。。。其实就是docker 命令前面没有加  sudo

**Comment by dazhu6666** [comment]
如果是直接自己操作。。。都要加sudu

**Comment by dazhu6666** [comment]
[ @anaconda ~]$ docker ps -a
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied
[ @anaconda ~]$

**Comment by dazhu6666** [comment]
加上 sudo就可以了

**Comment by yuzd** [comment]
我会更新的 稍等

**Comment by yuzd** [comment]
已更新 请用最新版试试
