### ISSUE TITLE
同一台机器 上想部署多个docker 实例，怎么操作

### ISSUE THREAD

**Issue by zenglei286** [yuzd/AntDeployAgent#40]
同一台机器 上想部署多个docker 实例，怎么操作，现在我是通过切换不同的env_name来进行实现的，有没有更简便一点的，一次上传，就批量建立不同的实例，每个实例不同的名称，不同的端口

**Comment by yuzd** [comment]
额 ，目前的设计是一个env 可以发布多个机器。每个机器发布的配置是走一样的。想走不一样的配置得需要不同的env。
目前没有考虑一个env不同的配置，改动有点大
