### ISSUE TITLE
为什么经常发布失败最新版不是6.4吗怎么老是提示升级6.8

### ISSUE THREAD

**Issue by apchenjun** [yuzd/AntDeployAgent#41]
![image](https://user-images.githubusercontent.com/4964551/113993394-05307200-9887-11eb-91f3-1889b0745439.png)

**Comment by yuzd** [comment]
提示的是你的agent呀

**Comment by apchenjun** [comment]
@yuzd 这个问题如何解决 https://github.com/yuzd/AntDeployAgent/issues/1 按照这个里面的 说明 做了还是不行

**Comment by apchenjun** [comment]
anent 服务 最新不是6.4吗 我安装后 第一次可以发布 成功 第二次 就发布失败 一直提示上面截图的问题 .net framework 和.net core 连个版本的agent都重新安装试过了
![image](https://user-images.githubusercontent.com/4964551/114006274-e59f4680-9892-11eb-99b2-8e315809b4e7.png)

**Comment by yuzd** [comment]
在群文件里面下载最新的agnet
