### ISSUE TITLE
AntDeploy服务安装后，测试时报500错误

### ISSUE THREAD

**Issue by yus1977** [yuzd/AntDeployAgent#42]
![image](https://user-images.githubusercontent.com/15851193/122519277-dc75e700-d044-11eb-873d-abcaa399ff98.png)

**Comment by yuzd** [comment]
服务安装成功了吗？
查看下是不是服务没有启动成功
再检查下端口号是否被禁用了。
另外agent请使用群里面的最新版

**Comment by yus1977** [comment]
这台服务器安装的AntDeploy服务已用了1年多，都一直可以正常发布应用
就这几天，不知到动了哪里，忽然就不正常了，提示上面的错误

**Comment by yuzd** [comment]
如果是用的独立版agent的话 ，因为netcore打包成独立exe的时候，点击这个exe会释放一些文件到temp目录。如果temp目录被删除了会导致启动不了。据说在net6会修复这个问题。到时候我会升级下。
如果你是遇到了上面的问题的话 你可以尝试卸载和删除服务然后重新安装

**Comment by yus1977** [comment]
可能是temp目录的原因
前段时间，这台服务器 因为temp目录文件太多，导致C盘快满了，所以把temp目录移到其它硬盘了

**Comment by yus1977** [comment]
我们在环境变量里把 temp改到了 d:\windows\temp
改回来后就正常了
多谢！！

**Comment by yuzd** [comment]
nice

**Comment by yuzd** [comment]
我发布了最新版本了，完美解决了这个问题了

**Comment by yus1977** [comment]
thanks!
