### ISSUE TITLE
配置项目启动

### ISSUE THREAD

**Issue by binwang951201** [yuzd/AntDeployAgent#44]
俞老师，首先要在本地安装jib.exe，antdeploy才能正常运行吗？

logger.Error($"can not found :{jibExe}");

**Comment by yuzd** [comment]
插件里面是带了这个jib.exe的呀。
是用来构建容器的

**Comment by binwang951201** [comment]
谢谢，我发现了，我在vs扩展安装目录下找到了这个exe,
project.DomainPath目录下没有发现这个exe

**Comment by yuzd** [comment]
嗯 因为有点占size，git ignore了
