### ISSUE TITLE
怎样才能排除指定文件夹的备份?

### ISSUE THREAD

**Issue by kugarliyifan** [yuzd/AntDeployAgent#9]
比如我想排除wwwroot下的uploads文件夹?

**Comment by kugarliyifan** [comment]
不用备份,也不用同步更新

**Comment by yuzd** [comment]
您好 你可以 看下https://github.com/yuzd/AntDeployAgent/issues/8
可以在setting 的tab界面的 Package Ignore Rule里面
添加一个排除规则 /wwwroot/uploads?.+
这样deploy 打包的时候就会排除这个文件夹了
然后在Windows Server BackUp IgnoreRule 也新增一条这个排除规则
代表备份的时候排除这个文件夹
